package main

import (
	"log"
	"os"

	echo "github.com/labstack/echo/v4"
	cli "github.com/urfave/cli/v2"
	_ "github.com/xsean2020/go-web-server/example/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/xsean2020/go-web-server/router"         // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2/api
func main() {
	log.Println((&cli.App{
		Name:        "echo-server",
		Usage:       "server",
		Version:     "v1.0.0",
		HideVersion: true,
		Description: "wrap for echo server",
		Authors:     []*cli.Author{},
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "config", Aliases: []string{"c"}, Value: "config.yaml", Usage: "config file"},
		},
		Action: func(c *cli.Context) error {
			e := echo.New()
			router.AddRoutersToEcho(e)
			return e.Start(":8080")
		},
	}).Run(os.Args))
}
